### ISSUE TITLE
lingui_macro_plugin.wasm

### ISSUE THREAD

**Issue by fengyunzaidushi** [yaakua/ai-outpainting-com#3]
yarn insatall
yarn dev
数据库在本地，迁移配置好了
出现下面错误
```
Caused by:
    0: failed to invoke E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\@lingui\swc-plugin\target\wasm32-wasi\release\lingui_macro_plugin.wasm as js transform plugin at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\@lingui\swc-plugin\target\wasm32-wasi\release\lingui_macro_plugin.wasm
    1: failed to run Wasm plugin transform. Please ensure the version of swc_core used by the plugin is compatible with the host runtime. See https://swc.rs/docs/plugin/selecting-swc-corefor compatibility information. If you are an author of the plugin, please update swc_core to the compatible version.
    2: RuntimeError: unreachable
           at __rust_start_panic (lingui_macro_plugin.wasm[3039]:0x13a7da)
           at rust_panic (lingui_macro_plugin.wasm[3034]:0x13a632)
           at std::panicking::rust_panic_with_hook::h50e657195af0239c (lingui_macro_plugin.wasm[3033]:0x13a3e8)
           at std::panicking::begin_panic_handler::{{closure}}::h0187e6969a85aab0 (lingui_macro_plugin.wasm[3020]:0x1397fd)
           at std::sys_common::backtrace::__rust_end_short_backtrace::h575fb82445d56667 (lingui_macro_plugin.wasm[3019]:0x139764)
           at rust_begin_unwind (lingui_macro_plugin.wasm[3028]:0x139f80)
           at core::panicking::panic_fmt::ha6764f2272b7fb95 (lingui_macro_plugin.wasm[3161]:0x147e0a)
           at core::result::unwrap_failed::had3752ac9f022e32 (lingui_macro_plugin.wasm[3199]:0x14e0b5)
           at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x13779)
           at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h9e0c654b5302067a (lingui_macro_plugin.wasm[185]:0x39677)
           at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x136c3)
           at swc_ecma_ast::stmt::_::<impl rkyv::Deserialize<swc_ecma_ast::stmt::Stmt,__D> for <swc_ecma_ast::stmt::Stmt as rkyv::Archive>::Archived>::deserialize::h9e0c654b5302067a (lingui_macro_plugin.wasm[185]:0x39677)
           at rkyv::impls::alloc::vec::<impl rkyv::Deserialize<alloc::vec::Vec<T>,D> for rkyv::vec::ArchivedVec<<T as rkyv::Archive>::Archived>>::deserialize::hc2f849ffa9291d17 (lingui_macro_plugin.wasm[77]:0x136c3)
           at swc_common::plugin::serialized::_::<impl rkyv::Deserialize<swc_common::plugin::serialized::VersionedSerializable<T>,__D> for <swc_common::plugin::serialized::VersionedSerializable<T> as rkyv::Archive>::Archived>::deserialize::ha91dd7c70adb26be (lingui_macro_plugin.wasm[75]:0x11eb2)
           at __transform_plugin_process_impl (lingui_macro_plugin.wasm[451]:0x5c65c)
           at __transform_plugin_process_impl.command_export (lingui_macro_plugin.wasm[3295]:0x154968)
Error: ENOENT: no such file or directory, open 'E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\fallback-build-manifest.json'
    at readFileSync (node:fs:448:20)
    at loadManifest (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\load-manifest.js:36:52)
    at loadManifestWithRetries (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\load-components.js:40:51)
    at async loadDefaultErrorComponentsImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\load-default-error-components.js:30:24)
    at async DevServer.getFallbackErrorComponents (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\dev\next-dev-server.js:594:16)
    at async DevServer.renderErrorToResponseImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:2187:40)      
    at async pipe.req.req (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:2040:30)
    at async DevServer.pipeImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:921:25)
    at async NextNodeServer.handleCatchallMiddlewareRequest (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\next-server.js:355:21)
    at async DevServer.handleRequestImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:823:28)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async handleRoute (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\lib\router-utils\resolve-routes.js:313:33)
    at async resolveRoutes (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\lib\router-utils\resolve-routes.js:530:28)
    at async handleRequest (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\lib\router-server.js:210:96)
    at async requestHandlerImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\lib\router-server.js:374:13)
    at async Server.requestListener (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\lib\start-server.js:141:13) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'E:\\share\\github\\010\\ai-outpainting-com2\\ai-outpainting-com\\.next\\fallback-build-manifest.json'
}
```
查看了这里好像是这个插件的原因：
https://rsbuild.dev/guide/basic/configure-swc

但目前还没有找到原因

**Comment by fengyunzaidushi** [comment]
```
Error: ENOENT: no such file or directory, open 'E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\fallback-build-manifest.json'
    at readFileSync (node:fs:448:20)
    at loadManifest (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\load-manifest.js:36:52)
    at loadManifestWithRetries (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\load-components.js:40:51)
    at async loadDefaultErrorComponentsImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\load-default-error-components.js:30:24)
    at async DevServer.getFallbackErrorComponents (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\dev\next-dev-server.js:594:16)
    at async DevServer.renderErrorToResponseImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:2187:40)      
    at async pipe.req.req (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:2040:30)
    at async DevServer.pipeImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:921:25)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\lib\router-server.js:173:21)
    at async requestHandlerImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\lib\router-server.js:386:24)
    at async Server.requestListener (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\lib\start-server.js:141:13) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'E:\\share\\github\\010\\ai-outpainting-com2\\ai-outpainting-com\\.next\\fallback-build-manifest.json'
}
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (684kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)   
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (684kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)   
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (685kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)   
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (685kiB) impacts deserialization performance (consider using Buffer instead and decode when needed) 
```
还是这个问题，
搞了1天了，还没安装成功

**Comment by fengyunzaidushi** [comment]
好像是和next.js相关：
https://www.reddit.com/r/nextjs/comments/v5xen9/nextjs_errror_node/
不过并没有看到 ud开头文件夹

**Comment by fengyunzaidushi** [comment]
在作者帮助下就觉了，要固定@lingui/swc-plugin": "4.0.8"版本， 原来是@lingui/swc-plugin": "^4.0.8"
去掉前面的箭头，然后删除node_modules和yarn.lock重新安装一下
