### ISSUE TITLE
yarn dev 后，google登录异常

### ISSUE THREAD

**Issue by fengyunzaidushi** [yaakua/ai-outpainting-com#4]
点击 sign in with google，跳转到页面
http://localhost:3000/api/auth/error/?error=Configuration
页面显示如下：
![image](https://github.com/user-attachments/assets/66ad9071-dba6-402f-9696-0101b2bd94d8)
控制台显示如下：
![image](https://github.com/user-attachments/assets/6be3e5ee-3aec-478e-aed8-ded45c2131b9)

终端显示如下：
```
[auth][error] TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getAuthorizationUrl (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/signin/authorization-url.js:23:35)
    at async Module.signIn (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/actions/signin/index.js:16:56)
    at async AuthInternal (webpack-internal:///(rsc)/./node_modules/@auth/core/lib/index.js:72:24)
    at async Auth (webpack-internal:///(rsc)/./node_modules/@auth/core/index.js:127:34)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:55778
    at async eO.execute (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:46527)
    at async eO.handle (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:57112)
    at async doRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1352:42)
    at async cacheEntry.responseCache.get.routeKind (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1562:40)
    at async DevServer.renderToResponseWithComponentsImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1482:28)
    at async DevServer.renderPageComponent (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1908:24)
    at async DevServer.renderToResponseImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1946:32)
    at async DevServer.pipeImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:921:25)
    at async NextNodeServer.handleCatchallRenderRequest (E:\share\github\010\ai-outpainting-com2\ai-out    at async NextNodeServer.handleCatchallRenderRequest (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:817:17)
painting-com\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:817:17)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\d    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modulesev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\trace\trace.js:154:20)
\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next    at async invokeRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\lib\router-server.js:173:21)
\dist\server\lib\router-server.js:173:21)
    at async handleRequest (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\nex    at async handleRequest (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\lib\router-server.js:350:24)
t\dist\server\lib\router-server.js:350:24)
    at async requestHandlerImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_module    at async requestHandlerImpl (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\lib\router-server.js:374:13)
    at async Server.requestListener (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\lib\start-server.js:141:13)
 POST /api/auth/signin/google/ 200 in 10044ms
 GET /api/auth/error/?error=Configuration 500 in 43ms
 ```

**Comment by fengyunzaidushi** [comment]
UE_GOOGLE_CLIENT_ID和UE_GOOGLE_CLIENT_SECRET都是配置正确的，没有问题。

**Comment by fengyunzaidushi** [comment]
根据readme.md说明，修改node_modules/@auth/core/node_modules/oauth4webapi/build/index.js
但是没有找到
![image](https://github.com/user-attachments/assets/eff80d75-50be-4079-a284-942a5475b71a)
但在这个路径找到了
\node_modules\oauth4webapi
按照说明，index.js 对应的代码都注释了，删除了.next文件夹，然后重新 yarn dev

遇到新的问题，

![image](https://github.com/user-attachments/assets/75e0edc9-6b43-4659-ad62-22218ef5b9ac)

问ai，console控制台添加http://localhost:3000/api/auth/callback/google
![image](https://github.com/user-attachments/assets/02b58630-6fd3-4b5f-9623-d78212e64b45)
已添加，还是出现问题

**Comment by yaakua** [comment]
google auth 配置和修改代码的说明已经增加了新的说明内容

**Comment by fengyunzaidushi** [comment]
找到问题了，是我的凭据不对！
