### ISSUE TITLE
yarn start之后无法登录

### ISSUE THREAD

**Issue by fengyunzaidushi** [yaakua/ai-outpainting-com#7]
```
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:49528
    at aD (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:52228)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Middleware called { url: 'http://localhost:3000/', method: 'GET' }
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:49528
    at aD (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:52228)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Middleware called { url: 'http://localhost:3000/en/', method: 'GET' }
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session/. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:49472
    at ij (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:52143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36957
    at async eC.execute (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:27552)
    at async eC.handle (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:38291)
    at async doRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1352:42)        
    at async cacheEntry.responseCache.get.routeKind (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1574:28)
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:49528
    at aD (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:52228)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Middleware called { url: 'http://localhost:3000/en/pricing/', method: 'GET' }
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:49528
    at aD (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:52228)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Middleware called { url: 'http://localhost:3000/en/blogs/', method: 'GET' }
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session/. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:49472
    at ij (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:52143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36957
    at async eC.execute (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:27552)
    at async eC.handle (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:38291)
    at async doRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1352:42)        
    at async cacheEntry.responseCache.get.routeKind (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1574:28)
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session/. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:49472
    at ij (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:52143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36957
    at async eC.execute (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:27552)
    at async eC.handle (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:38291)
    at async doRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1352:42)        
    at async cacheEntry.responseCache.get.routeKind (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1574:28)
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:49528
    at aD (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:52228)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Middleware called {
  url: 'http://localhost:3000/en/blogs/exploring-the-magic-of-ai-technology-to-extend-images-creatively/',
  method: 'GET'
}
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:49528
    at aD (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:52228)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Middleware called {
  url: 'http://localhost:3000/en/blogs/revolutionizing-image-editing-magic-ai-photo-outpainting-free/',
  method: 'GET'
}
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:49528
    at aD (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:52228)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Middleware called { url: 'http://localhost:3000/', method: 'GET' }
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:49528
    at aD (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:52228)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Middleware called { url: 'http://localhost:3000/en/', method: 'GET' }
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:49528
    at aD (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:52228)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Middleware called { url: 'http://localhost:3000/zh-TW/', method: 'GET' }
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session/. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:49472
    at ij (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:52143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36957
    at async eC.execute (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:27552)
    at async eC.handle (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:38291)
    at async doRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1352:42)        
    at async cacheEntry.responseCache.get.routeKind (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1574:28)
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:49528
    at aD (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:52228)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Middleware called { url: 'http://localhost:3000/zh-TW/pricing/', method: 'GET' }
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:49528
    at aD (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:52228)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Middleware called { url: 'http://localhost:3000/zh-TW/blogs/', method: 'GET' }
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session/. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:49472
    at ij (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:52143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36957
    at async eC.execute (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:27552)
    at async eC.handle (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:38291)
    at async doRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1352:42)        
    at async cacheEntry.responseCache.get.routeKind (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1574:28)
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session/. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:49472
    at ij (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:52143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36957
    at async eC.execute (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:27552)
    at async eC.handle (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:38291)
    at async doRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1352:42)        
    at async cacheEntry.responseCache.get.routeKind (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1574:28)
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session/. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:49472
    at ij (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:52143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36957
    at async eC.execute (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:27552)
    at async eC.handle (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:38291)
    at async doRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1352:42)        
    at async cacheEntry.responseCache.get.routeKind (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1574:28)
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session/. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:49472
    at ij (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:52143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36957
    at async eC.execute (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:27552)
    at async eC.handle (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:38291)
    at async doRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1352:42)        
    at async cacheEntry.responseCache.get.routeKind (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1574:28)
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session/. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:49472
    at ij (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:52143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36957
    at async eC.execute (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:27552)
    at async eC.handle (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:38291)
    at async doRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1352:42)        
    at async cacheEntry.responseCache.get.routeKind (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1574:28)
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/providers/. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:49472
    at ij (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:52143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36957
    at async eC.execute (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:27552)
    at async eC.handle (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:38291)
    at async doRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1352:42)        
    at async cacheEntry.responseCache.get.routeKind (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1574:28)
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/error/. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:49472
    at ij (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:52143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36957
    at async eC.execute (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:27552)
    at async eC.handle (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:38291)
    at async doRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1352:42)        
    at async cacheEntry.responseCache.get.routeKind (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1574:28)
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:49528
    at aD (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:52228)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Middleware called { url: 'http://localhost:3000/en/', method: 'GET' }
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:49528
    at aD (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\middleware.js:380:52228)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Middleware called { url: 'http://localhost:3000/en/pricing/', method: 'GET' }
[auth][error] UntrustedHost: Host must be trusted. URL was: http://localhost:3000/api/auth/session/. Read more at https://errors.authjs.dev#untrustedhost
    at E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:49472
    at ij (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\.next\server\chunks\6743.js:368:52143)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36957
    at async eC.execute (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:27552)
    at async eC.handle (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:38291)
    at async doRender (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1352:42)        
    at async cacheEntry.responseCache.get.routeKind (E:\share\github\010\ai-outpainting-com2\ai-outpainting-com\node_modules\next\dist\server\base-server.js:1574:28)
    ```
![image](https://github.com/user-attachments/assets/213c831e-02f3-40a2-9a1e-41d48c956ba2)

**Comment by fengyunzaidushi** [comment]
.env.production添加：
NEXTAUTH_URL=http://localhost:3000
AUTH_TRUST_HOST=true
